# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Distinguished Revolver
# email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
 >
 Many Precision Pistol shooters have a hard time making accurate .38 Special 158
 gr. lead ammunition for the NRA Distinguished Revolver event. What powder, what
 case, what bullet, etc. are all questions that frequently arise in the course
 of building an accurate load. To make matters even more difficult, not all
 revolvers are created equal, and so what works in one may very well not work in
 another, it is often said.

 >
 Strange, though, that many believe factory ammunition
 to be a great source of accuracy, which immediately goes against all lore and
 narrative of most reloading shooters; i.e. that they alone can make better and
 more accurate ammunition than the factory.

 >
 Here, I'll attempt to dispell myths, provide load data, and provide evidence
 for what appear to be significantly well understood and broadly accepted
 accurate loads to help cut load development time down considerably.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
github_username:  w4ti

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
